Improvements by revansurik
knyghtmare/a-song-of-fire pull request #3
Opened 2024-12-18 07:26 UTC by rodolphecombe

2025-03-19 10:17 UTC, knyghtmare commented
> ommented [on Dec 18, 2024](https://github.com/knyghtmare/wesnoth-A_Song_of_Fire/pull/3#issue-2747015351)
December 18th...? Wait...just how...?
You could pinged me at WMG

2025-03-19 10:23 UTC, knyghtmare requested changes

2025-03-19 10:23 UTC, knyghtmare commented on utils/characters.cfg
>  #define THELYAN
You change name... but leave macro as is?

2025-03-19 10:23 UTC, knyghtmare commented on changelog.txt
> -V 1.0.7
Why is all of the recent porting changelog entries being deleted?

2025-03-19 11:20 UTC, rodolphecombe commented on changelog.txt
> -V 1.0.7
That one is weird. I will fix it

2025-03-19 11:23 UTC, rodolphecombe commented on utils/characters.cfg
>  #define THELYAN
I can change it but that probably means changing several more files.

2025-03-20 08:01 UTC, rodolphecombe commented on utils/characters.cfg
>  #define THELYAN
Done

2025-03-20 08:01 UTC, rodolphecombe commented on changelog.txt
> -V 1.0.7
Done

2025-03-20 14:24 UTC, knyghtmare approved these changes

2025-03-20 14:26 UTC, merged